### ISSUE TITLE
Ansible-lint failures

### ISSUE THREAD

**Issue by DanTheFishGod** [shrikeh/ansible-haveged#3]
- [ANSIBLE0002] Trailing whitespace on tasks/main.yml lines:17-19
- [ANSIBLE0011] All tasks should be named on test/playbook.yml:4

**Comment by DanTheFishGod** [comment]
https://github.com/shrikeh-ansible-roles/ansible-haveged/pull/4

**Comment by shrikeh** [comment]
Merged #4
